server {
    listen 80;
    listen [::]:80;
    server_name mymine.mirv.top;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name auth.mymine.mirv.top;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name mymine.mirv.top;

    ssl_certificate /etc/letsencrypt/live/mymine.mirv.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mymine.mirv.top/privkey.pem;

    location = /map {
        return 301 /map/;
    }

    location /map/ {
        proxy_pass http://127.0.0.1:44447/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 1h;
    }

    location / {
        proxy_pass http://127.0.0.1:44445;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name auth.mymine.mirv.top;

    ssl_certificate /etc/letsencrypt/live/mymine.mirv.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mymine.mirv.top/privkey.pem;
    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:44446;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }
}
