server {
    listen 80;
    listen [::]:80;
    server_name mymine.mirv.top auth.mymine.mirv.top;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
